//! Report storage for the GUI: saved research reports with metadata, kept
//! under the user's Application Support directory.

use std::path::{Path, PathBuf};

use anyhow::{bail, Context as _, Result};
use serde::{Deserialize, Serialize};

/// Metadata stored next to each saved report (one `<stem>.json` per
/// `<stem>.md`).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ReportMeta {
    pub question: String,
    pub saved_at: String,
    pub freshness: u8,
    pub correctness: u8,
    pub coverage: u8,
    pub finding_count: usize,
    pub source_count: usize,
    pub iterations: u32,
}

#[derive(Clone, Debug)]
pub struct HistoryEntry {
    pub stem: String,
    pub meta: ReportMeta,
}

/// Directory-backed store. File stems are timestamps generated by this
/// store; anything else is rejected to keep paths inside the directory.
pub struct HistoryStore {
    dir: PathBuf,
}

impl HistoryStore {
    pub fn open_default() -> Result<Self> {
        let home = std::env::var("HOME").context("HOME is not set")?;
        let dir = Path::new(&home).join("Library/Application Support/agentic-search/reports");
        Self::open(dir)
    }

    pub fn open(dir: PathBuf) -> Result<Self> {
        std::fs::create_dir_all(&dir)
            .with_context(|| format!("failed to create {}", dir.display()))?;
        Ok(Self { dir })
    }

    pub fn dir(&self) -> &Path {
        &self.dir
    }

    /// Persist a report and its metadata; returns the new entry.
    pub fn save(&self, meta: ReportMeta, markdown: &str) -> Result<HistoryEntry> {
        let stem = chrono::Local::now().format("%Y%m%d-%H%M%S%.3f").to_string();
        std::fs::write(self.dir.join(format!("{stem}.md")), markdown)?;
        let json = serde_json::to_string_pretty(&meta)?;
        std::fs::write(self.dir.join(format!("{stem}.json")), json)?;
        Ok(HistoryEntry { stem, meta })
    }

    /// All saved reports, newest first.
    pub fn list(&self) -> Vec<HistoryEntry> {
        let Ok(dir) = std::fs::read_dir(&self.dir) else {
            return Vec::new();
        };
        let mut entries: Vec<HistoryEntry> = dir
            .flatten()
            .filter_map(|file| {
                let path = file.path();
                if path.extension()? != "json" {
                    return None;
                }
                let stem = path.file_stem()?.to_str()?.to_string();
                let meta = serde_json::from_str(&std::fs::read_to_string(&path).ok()?).ok()?;
                Some(HistoryEntry { stem, meta })
            })
            .collect();
        entries.sort_by(|a, b| b.stem.cmp(&a.stem));
        entries
    }

    pub fn load_markdown(&self, stem: &str) -> Result<String> {
        Ok(std::fs::read_to_string(self.checked_path(stem, "md")?)?)
    }

    pub fn delete(&self, stem: &str) -> Result<()> {
        std::fs::remove_file(self.checked_path(stem, "md")?).ok();
        std::fs::remove_file(self.checked_path(stem, "json")?)?;
        Ok(())
    }

    /// Build a path for a stem we issued; rejects separators and dots so a
    /// corrupted stem can never escape the store directory.
    fn checked_path(&self, stem: &str, ext: &str) -> Result<PathBuf> {
        let valid = !stem.is_empty()
            && stem
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '.');
        if !valid || stem.contains("..") {
            bail!("invalid report id: {stem}");
        }
        Ok(self.dir.join(format!("{stem}.{ext}")))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_store() -> HistoryStore {
        let dir = std::env::temp_dir().join(format!(
            "agentic-search-test-{}-{:?}",
            std::process::id(),
            std::time::Instant::now()
        ));
        HistoryStore::open(dir).unwrap()
    }

    fn meta(question: &str) -> ReportMeta {
        ReportMeta {
            question: question.to_string(),
            saved_at: "2026-06-10T00:00:00+09:00".into(),
            freshness: 80,
            correctness: 85,
            coverage: 90,
            finding_count: 10,
            source_count: 5,
            iterations: 2,
        }
    }

    #[test]
    fn save_list_load_delete_roundtrip() {
        let store = temp_store();
        let entry = store.save(meta("質問1"), "# レポート1").unwrap();

        let listed = store.list();
        assert_eq!(listed.len(), 1);
        assert_eq!(listed[0].meta.question, "質問1");
        assert_eq!(store.load_markdown(&entry.stem).unwrap(), "# レポート1");

        store.delete(&entry.stem).unwrap();
        assert!(store.list().is_empty());
        std::fs::remove_dir_all(store.dir()).unwrap();
    }

    #[test]
    fn list_returns_newest_first() {
        let store = temp_store();
        let first = store.save(meta("古い"), "a").unwrap();
        std::thread::sleep(std::time::Duration::from_millis(5));
        let second = store.save(meta("新しい"), "b").unwrap();

        let listed = store.list();
        assert_eq!(listed[0].stem, second.stem);
        assert_eq!(listed[1].stem, first.stem);
        std::fs::remove_dir_all(store.dir()).unwrap();
    }

    #[test]
    fn rejects_path_escaping_stems() {
        let store = temp_store();
        assert!(store.load_markdown("../outside").is_err());
        assert!(store.delete("a/b").is_err());
        assert!(store.delete("").is_err());
        std::fs::remove_dir_all(store.dir()).unwrap();
    }
}
